export interface PortfolioItem {
  id: string
  title: string
  description: string
  category: string
  highlightKeyword?: string
  image: string
  technologies: string[]
  demoUrl?: string
  githubUrl?: string
  completionDate?: string
  longDescription?: string
  features?: string[]
  process?: string
}

// Static data for fallback
export const portfolioItems: PortfolioItem[] = [
  {
    id: "backend-1",
    title: "Deshboard",
    description: "Deshboard for manage users and products and analytics.",
    category: "backend",
    highlightKeyword: "Laravel Dashboard",
    image: "/web/web-6.webp",
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "backend-2",
    title: "E-commerce Backend",
    description: "A scalable backend system for e-commerce platforms with inventory management.",
    category: "backend",
    highlightKeyword: "E-commerce",
    image: "/web/web-2.jpg",
    technologies: ["Node.js", "Express", "MongoDB", "Redis"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "June 2023",
    longDescription:
      "This e-commerce backend system was designed to handle high traffic and provide a seamless shopping experience. It includes features like real-time inventory management, order processing, and payment integration.",
    features: [
      "Real-time inventory tracking",
      "Secure payment processing",
      "Order management system",
      "User authentication and authorization",
    ],
  },
  {
    id: "backend-3",
    title: "E-Learning Backend",
    description: "E-learning backend system for manage users and courses and analytics.",
    category: "backend",
    highlightKeyword: "E-Learning",
    image: "/web/web-9.webp",
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "backend-4",
    title: "E-learning Dashboard",
    description: "E-learning dashboard for manage users and courses and analytics.",
    category: "backend",
    highlightKeyword: "React Dashboard",
    image: "/web/web-10.webp",
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "api-1",
    title: "E-commerce site API",
    description: "Secure payment processing API with multiple provider integrations and e-commerce features.",
    category: "api",
    highlightKeyword: "Payment",
    image: "/web/web-7.webp",
    technologies: ["Node.js", "Express", "Stripe API", "PayPal API"],
    githubUrl: "https://github.com/example/project",
    completionDate: "April 2023",
    features: [
      "Multi-provider payment processing",
      "Webhook integration",
      "Transaction reporting",
      "Fraud detection mechanisms",
    ],
  },
  {
    id: "api-2",
    title: "Product Management API",
    description: "Product management RESTful API with e-commerce features.",
    category: "api",
    highlightKeyword: "Product Management",
    image: "/web/web-8.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "api-3",
    title: "Inventory Management API",
    description: "inventory management RESTful API with e-commerce features.",
    category: "api",
    highlightKeyword: "Inventory",
    image: "/web/web-11.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "api-4",
    title: "E-learning API",
    description: "E-learning API for manage users and courses and analytics.",
    category: "api",
    highlightKeyword: "E-learning",
    image: "/web/web-10.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "backend-5",
    title: "Social Media Analytics API",
    description: "Comprehensive social media analytics API with sentiment analysis and trend tracking.",
    category: "api",
    highlightKeyword: "Analytics",
    image: "/web/web-1.webp",
    technologies: ["Node.js", "Express", "MongoDB", "Redis"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "October 2023",
    features: [
      "Sentiment analysis",
      "Trend tracking",
      "Real-time data processing",
      "Custom reporting",
    ],
  },
  {
    id: "backend-6",
    title: "Payment Gateway API",
    description: "Secure payment gateway API with multiple payment method support and fraud detection.",
    category: "api",
    highlightKeyword: "Payment",
    image: "/web/web-2.jpg",
    technologies: ["Python", "Django", "PostgreSQL", "Stripe"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "November 2023",
    features: [
      "Multiple payment methods",
      "Fraud detection",
      "Transaction logging",
      "Webhook integration",
    ],
  },
  {
    id: "backend-7",
    title: "File Management API",
    description: "Cloud-based file management API with upload, storage, and sharing capabilities.",
    category: "api",
    highlightKeyword: "File Management",
    image: "/web/web-3.jpg",
    technologies: ["Node.js", "Express", "AWS S3", "MongoDB"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "December 2023",
    features: [
      "File upload/download",
      "Cloud storage integration",
      "File sharing",
      "Version control",
    ],
  },
  {
    id: "backend-8",
    title: "Notification Service API",
    description: "Multi-channel notification service API supporting email, SMS, and push notifications.",
    category: "api",
    highlightKeyword: "Notifications",
    image: "/web/web-4.webp",
    technologies: ["Python", "FastAPI", "Redis", "Celery"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "January 2024",
    features: [
      "Multi-channel notifications",
      "Template management",
      "Delivery tracking",
      "Rate limiting",
    ],
  },
  {
    id: "mobile-1",
    title: "Food Ordering App",
    description: "Mobile application for ordering food with tracking workouts and nutrition with progress analytics.",
    category: "mobile",
    highlightKeyword: "Food",
    image: "/mobile/app-1.png",
    technologies: ["React Native", "Redux", "Firebase"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "March 2023",
    features: [
      "Workout tracking and planning",
      "Nutrition logging and analysis",
      "Progress visualization",
      "Social sharing capabilities",
    ],
  },
  {
    id: "mobile-2",
    title: "E-commerce App",
    description: "e-commerce app with payment processing and inventory management.",
    category: "mobile",
    highlightKeyword: "E-commerce",
    image: "/mobile/app-2.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-3",
    title: "Finance App",
    description: "finance app with stock market analysis and portfolio management.",
    category: "mobile",
    highlightKeyword: "Finance",
    image: "/mobile/app-3.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-4",
    title: "Weather App",
    description: "weather app with weather forecast and location tracking.",
    category: "mobile",
    highlightKeyword: "Weather",
    image: "/mobile/app-4.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-5",
    title: "Event Booking App",
    description: "event booking app with event planning and management.",
    category: "mobile",
    highlightKeyword: "Events",
    image: "/mobile/app-5.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-6",
    title: "Travel & Tour Guide App",
    description: "travel & tour guide app with travel planning and management.",
    category: "mobile",
    highlightKeyword: "Travel",
    image: "/mobile/app-6.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-7",
    title: "E-commerce App",
    description: "ecommerce app with e-commerce features.",
    category: "mobile",
    highlightKeyword: "E-commerce",
    image: "/mobile/app-7.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-8",
    title: "Food Recipe App",
    description: "food recipe app with food recipe features.",
    category: "mobile",
    highlightKeyword: "Recipes",
    image: "/mobile/app-8.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-9",
    title: "Fitness Tracking App",
    description: "Comprehensive fitness tracking app with workout plans, nutrition tracking, and progress analytics.",
    category: "mobile",
    highlightKeyword: "Fitness",
    image: "/mobile/app-1.png",
    technologies: ["React Native", "Redux", "Firebase"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "November 2023",
    features: [
      "Workout plan creation",
      "Nutrition tracking",
      "Progress analytics",
      "Social features",
    ],
  },
  {
    id: "mobile-10",
    title: "Language Learning App",
    description: "Interactive language learning app with gamification and speech recognition.",
    category: "mobile",
    highlightKeyword: "Language Learning",
    image: "/mobile/app-2.png",
    technologies: ["Flutter", "Dart", "TensorFlow Lite"],
    demoUrl: "https://example.com/demo",
    completionDate: "December 2023",
    features: [
      "Speech recognition",
      "Gamified learning",
      "Progress tracking",
      "Offline lessons",
    ],
  },
  {
    id: "mobile-11",
    title: "Meditation & Wellness App",
    description: "Meditation and wellness app with guided sessions and mood tracking.",
    category: "mobile",
    highlightKeyword: "Wellness",
    image: "/mobile/app-3.png",
    technologies: ["React Native", "Redux", "Firebase"],
    demoUrl: "https://example.com/demo",
    completionDate: "January 2024",
    features: [
      "Guided meditation sessions",
      "Mood tracking",
      "Sleep analytics",
      "Mindfulness reminders",
    ],
  },
  {
    id: "mobile-12",
    title: "Task Management App",
    description: "Productivity app with task management, project tracking, and team collaboration.",
    category: "mobile",
    highlightKeyword: "Productivity",
    image: "/mobile/app-4.png",
    technologies: ["Flutter", "Dart", "Firebase"],
    demoUrl: "https://example.com/demo",
    completionDate: "February 2024",
    features: [
      "Task management",
      "Project tracking",
      "Team collaboration",
      "Time tracking",
    ],
  },
  {
    id: "frontend-1",
    title: " Foxbridge Golf Club Website",
    description: "Modern marketing site for an 18‑hole Canadian golf course featuring tee‑time booking, simulator lounge details and membership info.",
    category: "frontend",
    highlightKeyword: "PHP",
    image: "/web/foxbridge.png",
    technologies: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "January 2023",
    features: [
      "Interactive data visualizations",
      "Real-time data updates",
      "Customizable dashboard layouts",
      "Export and reporting capabilities",
    ],
  },
  {
    id: "frontend-2",
    title: "SearchForce Solutions Portal",
    description: "Corporate landing & contact funnel for a health‑care automation provider, highlighting AI‑driven software and compliance services.",
    category: "frontend",
    highlightKeyword: "Healthcare",
    image: "/web/searchforce.png",
    technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-3",
    title: "VoiceHealth – Patient Voice Agents",
    description: "Product site showcasing 24/7 AI voice agents that automate calls, texts and scheduling for clinics and hospitals.",
    category: "frontend",
    highlightKeyword: "Frontend",
    image: "/web/voicehealth.png",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  
  {
    id: "frontend-4",
    title: "Allora – Decentralised AI Network",
    description: "Promotional single‑page that explains Allora's self‑improving, crypto‑powered ML network and drives Dev/Discord sign‑ups.",
    category: "frontend",
    highlightKeyword: "Dashboard",
    image: "/web/allora corporate.png",
    technologies: ["React", "Next.js", "Tailwind CSS", "Nunjucks"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-5",
    title: "Sasify – Clean SaaS Template",
    description: "High‑conversion SaaS Multi Page template with pricing, FAQ and CTA blocks ready to plug into any SaaS MVP.",
    category: "frontend",
    highlightKeyword: "SaaS",
    image: "/web/sasifyai.png",
    technologies: ["Next.js", "Tailwind CSS","TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-6",
    title: "Corporate Tech Website",
    description: "Service showcase for a California innovation company covering software, IoT, cloud and digital marketing.",
    category: "frontend",
    highlightKeyword: "Agency",
    image: "/web/wwt.png",
    technologies: ["Next.js", "Tailwind CSS","TypeScript" ,"Framer Motion", "React", "Payload CMS"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-7",
    title: "Way‑Wise Global Hub",
    description: "Gateway site that aggregates all subsidiary brands—tech, trading, travel, jobs—under one interactive umbrella.",
    category: "frontend",
    highlightKeyword: "Group Holding",
    image: "/web/waywiseglobal.png",
    technologies: ["Next.js", "Tailwind CSS","TypeScript" ,"Framer Motion", "React", "Payload CMS"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-8",
    title: "Man Power Agency",
    description: "International recruitment platform with country filters, application tracking and visa‑support workflows.",
    category: "frontend",
    highlightKeyword: "Man Power",
    image: "/web/waywisejobs.png",
    technologies: ["Next.js", "Tailwind CSS","TypeScript" , "React"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-9",
    title: "E-commerce Dashboard",
    description: "Modern e-commerce dashboard with analytics, order management, and inventory tracking.",
    category: "frontend",
    highlightKeyword: "E-commerce",
    image: "/web/web-5.webp",
    technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "June 2023",
    features: [
      "Sales analytics dashboard",
      "Order management system",
      "Inventory tracking",
      "Customer insights",
    ],
  },
  {
    id: "frontend-10",
    title: "Portfolio Website",
    description: "Creative portfolio website with smooth animations, project showcase, and contact forms.",
    category: "frontend",
    highlightKeyword: "Portfolio",
    image: "/web/web-6.webp",
    technologies: ["Next.js", "Tailwind CSS", "Framer Motion", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "July 2023",
    features: [
      "Project showcase gallery",
      "Smooth animations",
      "Contact form integration",
      "Responsive design",
    ],
  },
  {
    id: "frontend-11",
    title: "Blog Platform",
    description: "Modern blog platform with content management, user authentication, and social sharing.",
    category: "frontend",
    highlightKeyword: "Blog",
    image: "/web/web-7.webp",
    technologies: ["Next.js", "Tailwind CSS", "Prisma", "NextAuth"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Content management system",
      "User authentication",
      "Social sharing",
      "SEO optimization",
    ],
  },
  {
    id: "frontend-12",
    title: "Landing Page Builder",
    description: "Drag-and-drop landing page builder with customizable templates and analytics.",
    category: "frontend",
    highlightKeyword: "Landing Page",
    image: "/web/web-8.webp",
    technologies: ["React", "TypeScript", "Tailwind CSS", "DND Kit"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Drag-and-drop editor",
      "Template library",
      "Analytics integration",
      "Export functionality",
    ],
  },
  {
    id: "frontend-13",
    title: "Social Media Dashboard",
    description: "Comprehensive social media management dashboard with scheduling and analytics.",
    category: "frontend",
    highlightKeyword: "Social Media",
    image: "/web/web-9.webp",
    technologies: ["Next.js", "Tailwind CSS", "Chart.js", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "October 2023",
    features: [
      "Social media scheduling",
      "Analytics dashboard",
      "Content calendar",
      "Performance tracking",
    ],
  },
  {
    id: "frontend-14",
    title: "Project Management Tool",
    description: "Collaborative project management tool with task tracking, team communication, and file sharing.",
    category: "frontend",
    highlightKeyword: "Project Management",
    image: "/web/web-10.webp",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Socket.io"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "November 2023",
    features: [
      "Task management",
      "Team collaboration",
      "Real-time updates",
      "File sharing",
    ],
  },
  {
    id: "frontend-15",
    title: "Real-time Chat Application",
    description: "Modern real-time chat application with user authentication, file sharing, and message encryption.",
    category: "frontend",
    highlightKeyword: "Chat",
    image: "/web/web-11.webp",
    technologies: ["Next.js", "Tailwind CSS", "Socket.io", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "December 2023",
    features: [
      "Real-time messaging",
      "File sharing",
      "User authentication",
      "Message encryption",
    ],
  },
  {
    id: "frontend-16",
    title: "Data Visualization Platform",
    description: "Interactive data visualization platform with charts, graphs, and real-time data updates.",
    category: "frontend",
    highlightKeyword: "Data Visualization",
    image: "/web/web-1.webp",
    technologies: ["React", "D3.js", "Tailwind CSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "January 2024",
    features: [
      "Interactive charts",
      "Real-time data updates",
      "Customizable dashboards",
      "Export capabilities",
    ],
  },
  {
    id: "nocode-1",
    title: "Alumni Website",
    description: "This is a Wordpress website for alumni association.",
    category: "wordpress",
    highlightKeyword: "Wordpress",
    image: "/no-code/tayloralumni.png",
    technologies: ["Wordpress", "Elementor"],
    demoUrl: "https://example.com/demo",
    completionDate: "February 2023",
    features: [
      "Client onboarding workflow",
      "Document sharing and management",
      "Automated notifications",
      "Client feedback collection",
    ],
  },
  {
    id: "nocode-2",
    title: "Export Import Website",
    description: "This is a Wordpress website for export import company.",
    category: "wordpress",
    highlightKeyword: "Wordpress",
    image: "/no-code/waywisetrading.png",
    technologies: ["Wordpress", "Elementor"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "nocode-3",
    title: "Bulletproof Fitness",
    description: "Fitness website with fitness features design and easy to upload video and manage wordpress and Soppify.",
    category: "wordpress",
    highlightKeyword: "Wordpress",
    image: "/no-code/bulletprooffitness.png",
    technologies: ["Wordpress", "Elementor", "Soppify"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "nocode-4",
    title: "Wordpress Agency theme",
    description: "Wordpress Agency theme with Agency features and easy to manage.",
    category: "wordpress",
    highlightKeyword: "Wordpress",
    image: "/no-code/nc-4.webp",
    technologies: ["Wordpress", "Elementor", "PHP"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "wordpress-5",
    title: "Real Estate Website",
    description: "Professional real estate website with property listings, search filters, and contact forms.",
    category: "wordpress",
    highlightKeyword: "WordPress",
    image: "/no-code/no-code-05.jpg",
    technologies: ["Wordpress", "Elementor", "Real Estate Plugin"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Property listings management",
      "Advanced search filters",
      "Contact form integration",
      "Property image galleries",
    ],
  },
  {
    id: "wordpress-6",
    title: "Law Firm Website",
    description: "Professional law firm website with case studies, attorney profiles, and consultation booking.",
    category: "wordpress",
    highlightKeyword: "WordPress",
    image: "/no-code/no-code-06.jpg",
    technologies: ["Wordpress", "Elementor", "Booking Plugin"],
    demoUrl: "https://example.com/demo",
    completionDate: "November 2023",
    features: [
      "Attorney profile pages",
      "Case study showcase",
      "Consultation booking system",
      "Legal blog integration",
    ],
  },
  {
    id: "wordpress-7",
    title: "Medical Clinic Website",
    description: "Healthcare website with appointment scheduling, patient portal, and medical information.",
    category: "wordpress",
    highlightKeyword: "WordPress",
    image: "/no-code/nc-3.webp",
    technologies: ["Wordpress", "Elementor", "Medical Plugin"],
    demoUrl: "https://example.com/demo",
    completionDate: "December 2023",
    features: [
      "Appointment scheduling",
      "Patient portal access",
      "Medical information pages",
      "Doctor profiles",
    ],
  },
  {
    id: "wordpress-8",
    title: "Educational Institute Website",
    description: "Comprehensive educational website with course listings, student portal, and enrollment forms.",
    category: "wordpress",
    highlightKeyword: "WordPress",
    image: "/no-code/no-code-08.jpg",
    technologies: ["Wordpress", "Elementor", "LMS Plugin"],
    demoUrl: "https://example.com/demo",
    completionDate: "January 2024",
    features: [
      "Course catalog management",
      "Student portal integration",
      "Enrollment form system",
      "Faculty directory",
    ],
  },
  {
    id: "shopify-1",
    title: "Fashion E-commerce Store",
    description: "Modern fashion e-commerce store built with Shopify featuring product catalog, shopping cart, and payment processing.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-1.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Apps"],
    demoUrl: "https://example.com/demo",
    completionDate: "March 2023",
    features: [
      "Product catalog management",
      "Shopping cart functionality",
      "Payment gateway integration",
      "Order tracking system",
    ],
  },
  {
    id: "shopify-2",
    title: "Electronics Online Store",
    description: "Electronics e-commerce platform with advanced filtering, product reviews, and inventory management.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-2.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Plus"],
    demoUrl: "https://example.com/demo",
    completionDate: "May 2023",
    features: [
      "Advanced product filtering",
      "Customer review system",
      "Inventory management",
      "Multi-currency support",
    ],
  },
  {
    id: "shopify-3",
    title: "Home & Garden Store",
    description: "Home improvement e-commerce store with DIY guides, product recommendations, and installation services.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-3.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Apps"],
    demoUrl: "https://example.com/demo",
    completionDate: "June 2023",
    features: [
      "DIY guide integration",
      "Product recommendation engine",
      "Installation service booking",
      "Customer support chat",
    ],
  },
  {
    id: "shopify-4",
    title: "Sports Equipment Store",
    description: "Sports equipment e-commerce platform with size guides, equipment reviews, and training programs.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-4.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Plus"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Size guide integration",
      "Equipment review system",
      "Training program sales",
      "Athlete testimonials",
    ],
  },
  {
    id: "shopify-5",
    title: "Beauty & Cosmetics Store",
    description: "Beauty products e-commerce store with skin analysis, product matching, and beauty consultation.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-5.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Apps"],
    demoUrl: "https://example.com/demo",
    completionDate: "August 2023",
    features: [
      "Skin analysis tool",
      "Product matching algorithm",
      "Beauty consultation booking",
      "Loyalty program integration",
    ],
  },
  {
    id: "shopify-6",
    title: "Pet Supplies Store",
    description: "Pet supplies e-commerce platform with pet profiles, subscription services, and veterinary consultation.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-6.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Plus"],
    demoUrl: "https://example.com/demo",
    completionDate: "September 2023",
    features: [
      "Pet profile management",
      "Subscription service setup",
      "Veterinary consultation booking",
      "Pet care guides",
    ],
  },
  {
    id: "shopify-7",
    title: "Automotive Parts Store",
    description: "Automotive parts e-commerce store with vehicle compatibility checker, installation guides, and expert support.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-7.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Apps"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Vehicle compatibility checker",
      "Installation guide videos",
      "Expert support chat",
      "Warranty management",
    ],
  },
  {
    id: "shopify-8",
    title: "Jewelry & Accessories Store",
    description: "Luxury jewelry e-commerce platform with customization options, engraving services, and gift wrapping.",
    category: "shopify",
    highlightKeyword: "Shopify",
    image: "/no-code/shopify-8.jpg",
    technologies: ["Shopify", "Liquid", "Shopify Plus"],
    demoUrl: "https://example.com/demo",
    completionDate: "November 2023",
    features: [
      "Customization options",
      "Engraving service integration",
      "Gift wrapping selection",
      "Certificate of authenticity",
    ],
  },
  {
    id: "wix-1",
    title: "Restaurant Website",
    description: "Professional restaurant website with online ordering, menu display, and reservation system.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-3.webp",
    technologies: ["Wix", "Wix Editor", "Wix Apps"],
    demoUrl: "https://example.com/demo",
    completionDate: "April 2023",
    features: [
      "Online food ordering",
      "Menu management system",
      "Table reservation",
      "Customer testimonials",
    ],
  },
  {
    id: "wix-2",
    title: "Photography Portfolio",
    description: "Elegant photography portfolio website showcasing professional work with gallery and contact forms.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-4.webp",
    technologies: ["Wix", "Wix Editor", "Wix Gallery"],
    demoUrl: "https://example.com/demo",
    completionDate: "June 2023",
    features: [
      "Photo gallery showcase",
      "Portfolio management",
      "Contact form integration",
      "Social media integration",
    ],
  },
  {
    id: "wix-3",
    title: "Fitness Studio Website",
    description: "Fitness studio website with class scheduling, trainer profiles, and membership management.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-1.webp",
    technologies: ["Wix", "Wix Editor", "Wix Bookings"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Class scheduling system",
      "Trainer profile pages",
      "Membership management",
      "Workout video library",
    ],
  },
  {
    id: "wix-4",
    title: "Event Planning Website",
    description: "Event planning company website with portfolio showcase, service packages, and client testimonials.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-2.webp",
    technologies: ["Wix", "Wix Editor", "Wix Forms"],
    demoUrl: "https://example.com/demo",
    completionDate: "August 2023",
    features: [
      "Event portfolio showcase",
      "Service package display",
      "Client testimonial section",
      "Quote request forms",
    ],
  },
  {
    id: "wix-5",
    title: "Consulting Firm Website",
    description: "Professional consulting firm website with service offerings, team profiles, and case studies.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-3.webp",
    technologies: ["Wix", "Wix Editor", "Wix Blog"],
    demoUrl: "https://example.com/demo",
    completionDate: "September 2023",
    features: [
      "Service offering pages",
      "Team profile showcase",
      "Case study presentations",
      "Industry blog integration",
    ],
  },
  {
    id: "wix-6",
    title: "Travel Agency Website",
    description: "Travel agency website with destination guides, booking forms, and travel packages.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-4.webp",
    technologies: ["Wix", "Wix Editor", "Wix Bookings"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Destination guide pages",
      "Travel package display",
      "Booking form integration",
      "Travel blog section",
    ],
  },
  {
    id: "wix-7",
    title: "Interior Design Studio",
    description: "Interior design studio website with project portfolio, design services, and client consultation booking.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-1.webp",
    technologies: ["Wix", "Wix Editor", "Wix Gallery"],
    demoUrl: "https://example.com/demo",
    completionDate: "November 2023",
    features: [
      "Project portfolio gallery",
      "Design service pages",
      "Consultation booking system",
      "Before/after showcases",
    ],
  },
  {
    id: "wix-8",
    title: "Marketing Agency Website",
    description: "Digital marketing agency website with service offerings, client testimonials, and case study presentations.",
    category: "wix",
    highlightKeyword: "Wix",
    image: "/no-code/nc-2.webp",
    technologies: ["Wix", "Wix Editor", "Wix Analytics"],
    demoUrl: "https://example.com/demo",
    completionDate: "December 2023",
    features: [
      "Marketing service pages",
      "Client testimonial section",
      "Case study presentations",
      "Performance analytics",
    ],
  },
  {
    id: "webflow-1",
    title: "Creative Agency Website",
    description: "Modern creative agency website with custom animations, portfolio showcase, and lead generation forms.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-1.webp",
    technologies: ["Webflow", "Webflow CMS", "Custom CSS"],
    demoUrl: "https://example.com/demo",
    completionDate: "August 2023",
    features: [
      "Custom animations",
      "Portfolio showcase",
      "Lead generation forms",
      "Content management system",
    ],
  },
  {
    id: "webflow-2",
    title: "SaaS Landing Page",
    description: "High-converting SaaS landing page with interactive elements, pricing tables, and user testimonials.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-2.webp",
    technologies: ["Webflow", "Webflow Interactions", "Webflow CMS"],
    demoUrl: "https://example.com/demo",
    completionDate: "September 2023",
    features: [
      "Interactive elements",
      "Pricing table integration",
      "User testimonials",
      "Newsletter signup",
    ],
  },
  {
    id: "webflow-3",
    title: "E-commerce Platform",
    description: "Custom e-commerce platform with advanced product filtering, shopping cart, and payment integration.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-3.webp",
    technologies: ["Webflow", "Webflow E-commerce", "Webflow CMS"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Advanced product filtering",
      "Shopping cart functionality",
      "Payment gateway integration",
      "Inventory management",
    ],
  },
  {
    id: "webflow-4",
    title: "Educational Platform",
    description: "Online learning platform with course management, student progress tracking, and interactive lessons.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-4.webp",
    technologies: ["Webflow", "Webflow CMS", "Webflow Interactions"],
    demoUrl: "https://example.com/demo",
    completionDate: "November 2023",
    features: [
      "Course management system",
      "Student progress tracking",
      "Interactive lesson modules",
      "Certificate generation",
    ],
  },
  {
    id: "webflow-5",
    title: "Healthcare Platform",
    description: "Healthcare platform with appointment scheduling, patient portal, and telemedicine integration.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-1.webp",
    technologies: ["Webflow", "Webflow CMS", "Webflow Forms"],
    demoUrl: "https://example.com/demo",
    completionDate: "December 2023",
    features: [
      "Appointment scheduling system",
      "Patient portal access",
      "Telemedicine integration",
      "Medical record management",
    ],
  },
  {
    id: "webflow-6",
    title: "Real Estate Platform",
    description: "Real estate platform with property listings, virtual tours, and mortgage calculator integration.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-2.webp",
    technologies: ["Webflow", "Webflow CMS", "Webflow Interactions"],
    demoUrl: "https://example.com/demo",
    completionDate: "January 2024",
    features: [
      "Property listing management",
      "Virtual tour integration",
      "Mortgage calculator",
      "Agent profile pages",
    ],
  },
  {
    id: "webflow-7",
    title: "Financial Services Platform",
    description: "Financial services platform with investment tracking, portfolio management, and financial planning tools.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-3.webp",
    technologies: ["Webflow", "Webflow CMS", "Webflow E-commerce"],
    demoUrl: "https://example.com/demo",
    completionDate: "February 2024",
    features: [
      "Investment tracking dashboard",
      "Portfolio management tools",
      "Financial planning calculators",
      "Secure client portal",
    ],
  },
  {
    id: "webflow-8",
    title: "Entertainment Platform",
    description: "Entertainment platform with content streaming, user profiles, and social interaction features.",
    category: "webflow",
    highlightKeyword: "Webflow",
    image: "/no-code/nc-4.webp",
    technologies: ["Webflow", "Webflow CMS", "Webflow Interactions"],
    demoUrl: "https://example.com/demo",
    completionDate: "March 2024",
    features: [
      "Content streaming integration",
      "User profile management",
      "Social interaction features",
      "Content recommendation engine",
    ],
  },
  {
    id: "email-templates-1",
    title: "Email Templates",
    description: "Email templates with a focus on scalability and performance.",
    category: "email-templates",
    highlightKeyword: "Email Templates",
    image: "/email-template/email-template-1.png",
    technologies: ["Email Templates", "Email Templates", "Email Templates"],
  },
  {
    id: "email-templates-2",
    title: "Email Templates",
    description: "Email templates with a focus on scalability and performance.",
    category: "email-templates",
    highlightKeyword: "Email Templates",
    image: "/email-template/email-template-2.png",
    technologies: ["Email Templates", "Email Templates", "Email Templates"],
  },
  {
    id: "email-templates-3",
    title: "Email Templates",
    description: "Email templates with a focus on scalability and performance.",  
    category: "email-templates",
    highlightKeyword: "Email Templates",
    image: "/email-template/email-template-3.png",
    technologies: ["Email Templates", "Email Templates", "Email Templates"],
  },
  {
    id: "email-templates-4",
    title: "Email Templates",
    description: "Email templates with a focus on scalability and performance.",
    category: "email-templates",
    highlightKeyword: "Email Templates",
    image: "/email-template/email-template-4.png",
    technologies: ["Email Templates", "Email Templates", "Email Templates"],
  }
]

// Function to fetch portfolio items from API
export async function fetchPortfolioItems(): Promise<PortfolioItem[]> {
  try {
    const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || ''}/api/portfolio`, {
      cache: 'no-store'
    });
    
    if (!response.ok) {
      console.warn('Failed to fetch from API, using static data');
      return portfolioItems;
    }
    
    const data = await response.json();
    return data;
  } catch (error) {
    console.warn('Error fetching from API, using static data:', error);
    return portfolioItems;
  }
}

export const sectionInfo = {
  "backend": {
    "title": "Backend Projects",
    "description": "Explore my backend projects with a focus on scalability and performance."
  },
  "mobile": {
    "title": "Mobile App Projects",
    "description": "Discover my mobile app projects with a range of features and capabilities."
  },
  "frontend": {
    "title": "Frontend Projects",
    "description": "Check out my frontend projects with a focus on user experience and design."
  },
  "nocode": {
    "title": "No-code Projects",
    "description": "Explore my no-code projects with a range of features and capabilities."
  },
  "wordpress": {
    "title": "WordPress Projects",
    "description": "Discover my WordPress websites and themes built with modern design and functionality."
  },
  "shopify": {
    "title": "Shopify Projects",
    "description": "Explore my Shopify e-commerce stores with advanced features and custom solutions."
  },
  "wix": {
    "title": "Wix Projects",
    "description": "Check out my Wix websites with professional design and seamless user experience."
  },
  "webflow": {
    "title": "Webflow Projects",
    "description": "Discover my Webflow projects with custom animations and advanced interactions."
  },
  "api": {
    "title": "API Projects",
    "description": "Discover my API projects with a focus on scalability and performance."
  },
  "email-templates": {
    "title": "Email Templates",
    "description": "Discover my email templates with a focus on scalability and performance."
  },
  "react": {
    "title": "React Projects",
    "description": "Discover my React projects with a focus on scalability and performance."
  },
  "nextjs": {
    "title": "Next.js Projects",
    "description": "Discover my Next.js projects with a focus on scalability and performance."
  },
  "tailwind": {
    "title": "Tailwind Projects",
    "description": "Discover my Tailwind projects with a focus on scalability and performance."
  }
}
