export interface PortfolioItem {
  id: string
  title: string
  description: string
  category: string
  highlightKeyword?: string
  image: string
  technologies: string[]
  demoUrl?: string
  githubUrl?: string
  completionDate?: string
  longDescription?: string
  features?: string[]
  process?: string
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: "backend-1",
    title: "Deshboard",
    description: "Deshboard for manage users and products and analytics.",
    category: "backend-api",
    highlightKeyword: "Laravel Dashboard",
    image: "/web/web-6.webp",
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "backend-2",
    title: "E-commerce Backend",
    description: "A scalable backend system for e-commerce platforms with inventory management.",
    category: "backend-api",
    highlightKeyword: "E-commerce",
    image: "/web/web-2.jpg",
    technologies: ["Node.js", "Express", "MongoDB", "Redis"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "June 2023",
    longDescription:
      "This e-commerce backend system was designed to handle high traffic and provide a seamless shopping experience. It includes features like real-time inventory management, order processing, and payment integration.",
    features: [
      "Real-time inventory tracking",
      "Secure payment processing",
      "Order management system",
      "User authentication and authorization",
    ],
  },
  {
    id: "backend-3",
    title: "E-Learning Backend",
    description: "E-learning backend system for manage users and courses and analytics.",
    category: "backend-api",
    highlightKeyword: "E-Learning",
    image: "/web/web-9.webp",
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "backend-4",
    title: "E-learning Dashboard",
    description: "E-learning dashboard for manage users and courses and analytics.",
    category: "backend-api",
    highlightKeyword: "React Dashboard",
    image: "/web/web-10.webp",
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "api-1",
    title: "E-commerce site API",
    description: "Secure payment processing API with multiple provider integrations and e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Payment",
    image: "/web/web-7.webp",
    technologies: ["Node.js", "Express", "Stripe API", "PayPal API"],
    githubUrl: "https://github.com/example/project",
    completionDate: "April 2023",
    features: [
      "Multi-provider payment processing",
      "Webhook integration",
      "Transaction reporting",
      "Fraud detection mechanisms",
    ],
  },
  {
    id: "api-2",
    title: "Product Management API",
    description: "Product management RESTful API with e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Product Management",
    image: "/web/web-8.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "api-3",
    title: "Inventory Management API",
    description: "inventory management RESTful API with e-commerce features.",
    category: "backend-api",
    highlightKeyword: "Inventory",
    image: "/web/web-11.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "api-4",
    title: "E-learning API",
    description: "E-learning API for manage users and courses and analytics.",
    category: "backend-api",
    highlightKeyword: "E-learning",
    image: "/web/web-10.webp",
    technologies: ["Python", "FastAPI", "Redis", "Docker"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "September 2023",
    features: [
      "Multi-source data aggregation",
      "Historical weather data analysis",
      "Forecast prediction algorithms",
      "Geolocation-based queries",
    ],
  },
  {
    id: "mobile-1",
    title: "Food Ordering App",
    description: "Mobile application for ordering food with tracking workouts and nutrition with progress analytics.",
    category: "mobile",
    highlightKeyword: "Food",
    image: "/mobile/app-1.png",
    technologies: ["React Native", "Redux", "Firebase"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "March 2023",
    features: [
      "Workout tracking and planning",
      "Nutrition logging and analysis",
      "Progress visualization",
      "Social sharing capabilities",
    ],
  },
  {
    id: "mobile-2",
    title: "E-commerce App",
    description: "e-commerce app with payment processing and inventory management.",
    category: "mobile",
    highlightKeyword: "E-commerce",
    image: "/mobile/app-2.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-3",
    title: "Finance App",
    description: "finance app with stock market analysis and portfolio management.",
    category: "mobile",
    highlightKeyword: "Finance",
    image: "/mobile/app-3.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-4",
    title: "Weather App",
    description: "weather app with weather forecast and location tracking.",
    category: "mobile",
    highlightKeyword: "Weather",
    image: "/mobile/app-4.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-5",
    title: "Event Booking App",
    description: "event booking app with event planning and management.",
    category: "mobile",
    highlightKeyword: "Events",
    image: "/mobile/app-5.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-6",
    title: "Travel & Tour Guide App",
    description: "travel & tour guide app with travel planning and management.",
    category: "mobile",
    highlightKeyword: "Travel",
    image: "/mobile/app-6.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-7",
    title: "E-commerce App",
    description: "ecommerce app with e-commerce features.",
    category: "mobile",
    highlightKeyword: "E-commerce",
    image: "/mobile/app-7.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "mobile-8",
    title: "Food Recipe App",
    description: "food recipe app with food recipe features.",
    category: "mobile",
    highlightKeyword: "Recipes",
    image: "/mobile/app-8.png",
    technologies: ["Flutter", "Dart", "Google Maps API"],
    demoUrl: "https://example.com/demo",
    completionDate: "October 2023",
    features: [
      "Offline map functionality",
      "Itinerary planning and management",
      "Local recommendations engine",
      "Travel journal and photo storage",
    ],
  },
  {
    id: "frontend-1",
    title: " Foxbridge Golf Club Website",
    description: "Modern marketing site for an 18‑hole Canadian golf course featuring tee‑time booking, simulator lounge details and membership info.",
    category: "frontend",
    highlightKeyword: "PHP",
    image: "/web/foxbridge.png",
    technologies: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "January 2023",
    features: [
      "Interactive data visualizations",
      "Real-time data updates",
      "Customizable dashboard layouts",
      "Export and reporting capabilities",
    ],
  },
  {
    id: "frontend-2",
    title: "SearchForce Solutions Portal",
    description: "Corporate landing & contact funnel for a health‑care automation provider, highlighting AI‑driven software and compliance services.",
    category: "frontend",
    highlightKeyword: "Healthcare",
    image: "/web/searchforce.png",
    technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-3",
    title: "VoiceHealth – Patient Voice Agents",
    description: "Product site showcasing 24/7 AI voice agents that automate calls, texts and scheduling for clinics and hospitals.",
    category: "frontend",
    highlightKeyword: "Frontend",
    image: "/web/voicehealth.png",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  
  {
    id: "frontend-4",
    title: "Allora – Decentralised AI Network",
    description: "Promotional single‑page that explains Allora’s self‑improving, crypto‑powered ML network and drives Dev/Discord sign‑ups.",
    category: "frontend",
    highlightKeyword: "Dashboard",
    image: "/web/allora corporate.png",
    technologies: ["React", "Next.js", "Tailwind CSS", "Nunjucks"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "frontend-5",
    title: "Allora – Decentralised AI Network",
    description: "Promotional single‑page that explains Allora’s self‑improving, crypto‑powered ML network and drives Dev/Discord sign‑ups.",
    category: "frontend",
    highlightKeyword: "Dashboard",
    image: "/web/allora corporate.png",
    technologies: ["React", "Next.js", "Tailwind CSS", "Nunjucks"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "May 2023",
    features: [
      "Course content management",
      "Progress tracking and analytics",
      "Interactive quizzes and assessments",
      "Certificate generation",
    ],
  },
  {
    id: "nocode-1",
    title: "Alumni Website",
    description: "This is a Wordpress website for alumni association.",
    category: "nocode",
    highlightKeyword: "Wordpress",
    image: "/no-code/tayloralumni.png",
    technologies: ["Wordpress", "Elementor"],
    demoUrl: "https://example.com/demo",
    completionDate: "February 2023",
    features: [
      "Client onboarding workflow",
      "Document sharing and management",
      "Automated notifications",
      "Client feedback collection",
    ],
  },
  {
    id: "nocode-2",
    title: "Export Import Website",
    description: "This is a Wordpress website for export import company.",
    category: "nocode",
    highlightKeyword: "Wordpress",
    image: "/no-code/waywisetrading.png",
    technologies: ["Wordpress", "Elementor"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "nocode-3",
    title: "Bulletproof Fitness",
    description: "Fitness website with fitness features design and easy to upload video and manage wordpress and Soppify.",
    category: "nocode",
    highlightKeyword: "Wordpress",
    image: "/no-code/bulletprooffitness.png",
    technologies: ["Wordpress", "Elementor", "Soppify"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
  {
    id: "nocode-4",
    title: "Wordpress Agency theme",
    description: "Wordpress Agency theme with Agency features and easy to manage.",
    category: "nocode",
    highlightKeyword: "Wordpress",
    image: "/no-code/nc-4.webp",
    technologies: ["Wordpress", "Elementor", "PHP"],
    demoUrl: "https://example.com/demo",
    completionDate: "July 2023",
    features: [
      "Subscription management",
      "Content access control",
      "Member directory and profiles",
      "Integrated payment processing",
    ],
  },
]


export const sectionInfo = {
  "backend": {
    "title": "Backend Projects",
    "description": "Explore my backend projects with a focus on scalability and performance."
  },
  "mobile": {
    "title": "Mobile Projects",
    "description": "Discover my mobile app projects with a range of features and capabilities."
  },
  "frontend": {
    "title": "Frontend Projects",
    "description": "Check out my frontend projects with a focus on user experience and design."
  },
  "nocode": {
    "title": "No-code Projects",
    "description": "Explore my no-code projects with a range of features and capabilities."
  },
  "api": {
    "title": "API Projects",
    "description": "Discover my API projects with a focus on scalability and performance."
  }

}
